version: "3.8"

services:
  reservation-bot:
    build: .
    volumes:
      - ./account.csv:/app/account.csv:ro
      - ./screenshots:/app/screenshots
    environment:
      - PYTHONUNBUFFERED=1
    restart: "no"

#1. Docker Desktop インストール
#2. Dockerfile と docker-compose.yml と requirements.txtをダウンロード
#3. account.csv を同じフォルダに置く
#4. cmdで docker-compose create --build
#5. 実行したいときはreservation-botを起動